# fly.toml app configuration file generated for acto on 2025-04-18T18:33:37+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'acto'
primary_region = 'lhr'

[build]

[mounts]
source = "acto_data"
destination = "/data"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
max_machines_running = 1
processes = ['app']

[[vm]]
memory = '256mb'
cpu_kind = 'shared'
cpus = 1
