import type { Metadata, Viewport } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import AuthProvider from '@/components/AuthProvider';
import ClientPWAWrapper from '@/components/ClientPWAWrapper';

const poppins = Poppins({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-poppins',
  display: 'swap',
});

export const viewport: Viewport = {
  themeColor: '#000000',
  viewportFit: 'cover',
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export const metadata: Metadata = {
  title: 'acto - Interactive Story',
  description: 'Embark on thrilling interactive storys powered by AI.',
  keywords: 'interactive story, AI story, storytelling, RPG, story',
  authors: [{ name: 'acto Team' }],
  metadataBase: new URL('https://acto.app'),
  openGraph: {
    title: 'acto - AI-Powered Interactive Storys',
    description: 'Play captivating interactive storys generated by AI.',
    locale: 'en_US',
    type: 'website',
  },
  manifest: '/manifest.json',
  appleWebApp: {
    capable: true,
    statusBarStyle: 'default',
    title: 'acto',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'acto',
    description: 'Experience interactive storys brought to life by AI.',
  },
  icons: {
    icon: '/favicon.ico',
    apple: '/apple-touch-icon.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
        <link rel="icon" href="/icons/icon-192x192.png" />
        <link rel="apple-touch-icon" href="/icons/icon-192x192.png" />
      </head>
      <body className={`${poppins.variable} font-sans`}>
        <AuthProvider>
          {children}
          <ClientPWAWrapper />
        </AuthProvider>
      </body>
    </html>
  );
}
