name: Fly Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Restore Next.js cache
        uses: actions/cache@v3
        id: next-cache
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.ts', '**/*.tsx', 'next.config.js*') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Install dependencies
        run: npm ci

      - name: Run code quality checks
        run: npm run verify

      - name: Run tests
        run: npm test

      - name: Setup Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: |
          flyctl deploy --dockerfile Dockerfile --remote-only \
            --build-arg NEXT_CACHE_DIR=${{ steps.next-cache.outputs.cache-hit && './.next/cache' || '' }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          # SENTRY ARGS (Pass if required during build, check Dockerfile ARG declarations)
          # NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}
          # SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          # SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          # SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
